### ISSUE TITLE
Crash: NPE from FluidTankWrapper

### ISSUE THREAD

**Issue by utoc** [McJty/DeepResonance#121]
Crash here: http://pastebin.com/p99nUwnj

Running
deepresonance-1.10-1.2.8
mcjtylib-1.10-2.1.3
rftools-1.10-5.26
EnderCore-1.10.2-0.4.1.56-beta
EnderIO-1.10.2-3.0.1.116_beta
fml 2095

Scenario: Someone was drowning in lava and teleported away to their base to prevent a very fluid death.  Bam.  Crash.

Full FML log: https://gist.github.com/utoc/2d8274a775a44cfdb3bd07fa3981e542

Incidently we had a watchdog crash earlier involving EIO conduits but I don't know if they're related: https://github.com/SleepyTrousers/EnderIO/issues/3524#issuecomment-251502525

**Comment by McJty** [comment]
Did you also report this to EnderIO?

**Comment by utoc** [comment]
This crash?  No.  Want me to?

**Comment by McJty** [comment]
yes sure. It can be on their end too

**Comment by HenryLoenwind** [comment]
Not really, the call on our end is:

```
return fluidHandler.drain(Integer.MAX_VALUE, false);
```

Not many possibilities to sneak a null value in ;)

**Comment by McJty** [comment]
Ok. I'll check it out

**Comment by MrNinja93** [comment]
If it helps also had this crash twice, Server side only (just over a fortnight ago, have since updated mods)

Once with players on-line and nearby once with no players, though I believe the area in question was chunkloaded at the time.

http://pastebin.com/xTep8z58 (with players)
http://pastebin.com/p7fHKY6T (Without players)

The crash with players was with a conduit bundle that was redstone and fluid conduit set up to a lava tank for smelting resonating ore auto set up to keep 50% lava in the lower tank with the RFtools fluid monitor activating the redstone conduit to keep that lower tank around 50% lava.

**Comment by MrNinja93** [comment]
Server just now had this crash again, no one online. 

Attaching screenshots of offending setup this time. players system wasn't running at the time.
Ender conduit unfiltered set to auto extract from tank which is auto pushing liquids out (no liquid was in the system at the time, Valve above was also disabled by redstone)

![2016-10-24_01 20 32](https://cloud.githubusercontent.com/assets/21979276/19630735/9023417e-9988-11e6-9e38-580d6ad9b528.png)
![2016-10-24_01 20 37](https://cloud.githubusercontent.com/assets/21979276/19630736/902a22f0-9988-11e6-8333-86676622ff56.png)
![2016-10-24_01 27 00](https://cloud.githubusercontent.com/assets/21979276/19630768/2bc8f2b8-9989-11e6-8884-5aede15df367.png)
![2016-10-24_01 27 17](https://cloud.githubusercontent.com/assets/21979276/19630769/2bcf1fe4-9989-11e6-93ed-f478c316fca3.png)
![2016-10-24_01 20 37](https://cloud.githubusercontent.com/assets/21979276/19630770/2bd615ec-9989-11e6-8261-13bc192bf10a.png)

## Server Crash log
http://pastebin.com/sXuWTRvd

**Comment by McJty** [comment]
Update ElecCore. This has been fixed
