### ISSUE TITLE
[1.12] Tank cannot handle any liquid

### ISSUE THREAD

**Issue by ExDomino** [McJty/DeepResonance#216]
The tank, that is supposed to handle lava in order to smelt resonating ore, cannot handle any liquid.
Deep Resonance : 1.4.8.

https://image.noelshack.com/fichiers/2017/28/4/1499972958-2017-07-13-15-08-33.png
On this screenshot, the tank is set to blue. It doesn't work either for orange.
We tryed to right click with a lava bucket to fill the tank, but it doesn't work either.

When a mod has this kind of bug, it's not a release, it's a beta, or an alpha.

**Comment by McJty** [comment]
Well it works for me. Is the fluid conduit below it configured correctly? Did you try with other fluid transportation mechanisms?

**Comment by ExDomino** [comment]
Tryed blue and orange. Tryed with a simple Lava Bucket. Doesn't work!
How it is supposed to work?

**Comment by McJty** [comment]
I mean, is the fluid conduit itself configured correctly (not the tank)?

**Comment by McJty** [comment]
Hmm, but it is indeed not working with a bucket. That's a bug

**Comment by ExDomino** [comment]
The fluid pipe has not setting to put a liquid into a tank. Just a "Servo" to withdraw it.
Where your Tank is supposed to take liquid? Under? Over? Sides?

**Comment by McJty** [comment]
Nm, there is something wrong. I'll investigate.
@Elec332 can you look at this?

**Comment by ExDomino** [comment]
McJty, you said it worked for you, so during your test, how you did the lava inside the tank?

**Comment by McJty** [comment]
I must have tested the wrong version or something because it isn't working for me anymore either

**Comment by ExDomino** [comment]
Ok, we'll wait for a fix.

**Comment by DingoX3** [comment]
Can confirm this issue. Seems as though the block is remembering its fluid level state. I can remove the tank and look at it in my inventory it will say 6000mb or so. Then when i place it somewhere else on the ground theres no fluid in it. Then if i place a newly crafted tank in the same location under the smelter it then appears as if it has the same amount of lava the previous tank had in it. So thats not allowing more to be piped in im guessing. Same issue occurs with the tanks that have liquid crystal in it. I remove the block, it says theres fluid in it, place down it on ground, no fluid. Then place a new tank where it was above the smelter and i see the fluid but now it doesnt register the percentages of the fluid. I hope this helps track down the issues. Thanks for all your hard work.

**Comment by HugeLol556** [comment]
I too have this problem, in AllTheMods/ATM-3 as Darkere has referenced. 

The mod is almost completely unusable in multiplayer because tanks will randomly "break." "Break" as in refuse to accept/transfer any liquids and will not interact with its fellow deep resonance machines, smelter, crystalizer, etc, or other mods. Breaking and replacing "broken" tanks will not fix the issue. The only way to fix this "break" is to simply reload the server, easy in single player, but you see how it becomes troublesome when trying to play with friends, which in my case is through LAN.     

I'm having trouble replicating this error because I am cannot seem to figure out what triggers the tanks to "break." One thing I am positive about, at least to an extent since I tested it in a single player world, is that newly placed tanks automatically "break" upon placement and require the restart.

Finally there seems to be a similar error effecting both the smelter and valve, simply breaking them and replacing them will fix it though.

 Here is my personal experience: I'm playing on a LAN server my friend is hosting. Last night my crystal factory's crystalizer, the factory you helped me build with your guide, seemed to be broken so I just said "f*** it* and quit. Today I rejoined, and voila, the crystalizer that wasn't crystalizing before had gone from 20% to about 70% while I was gone. But then I noticed it wasn't working AGAIN, because there was still RCL in the tank. Eventually I realized today's error was because of the previously mentioned tank "break." I am sadly clueless about last night's though.

**Comment by McJty** [comment]
We are investigating this bug. Hopefully it will get resolved soon

**Comment by ExDomino** [comment]
We can use the mod if we place the tank on the ground, restart the server and don't move the tank after.

**Comment by winsrp** [comment]
I have a similar bug to this, but its kind of weird, I'll try to explain.

I put a tank on the floor and grab a bucket of lava. So I put in the lava in the tank. All good, then I break the tank (dispose that tank an grab a new one from creative tab) and put 3 tanks using the same location as the tank from before and it seems to remember how much of the lava was in the previous tank. 

Same with smelted material, these tanks behave really weird.

**Comment by HugeLol556** [comment]
UPDATE: Keeping the chunks loaded seemed to fixed the tank from randomly breaking. LAN world reopened and upon joining tanks were in perfect working order, BUT smelter, valve, AND crystalizer stopped working, forcing me to break and replace them to get them to work again. Luckily my crystalizer was at 0%, but this glitch could have serious consequences.

**Comment by Elec332** [comment]
Please update to latest ElecCore
