### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by kittykiller** [McJty/DeepResonance#39]
Not sure which mod is causing it so reporting it to both mods.

http://pastebin.com/NhzpR3Qg

**Comment by iggythemad** [comment]
Had exactly same issue with that yesterday.

In my case it happened when I put the tank above the smeltery. However, as the smeltery processed the resonant ore and should have practically put liquid into the tank on top, it didn't. Trying to analyse that, I dismantled the tank - and that's when the server crash would occur.

This mostly occured when I was first trying to work the tank with liquid pipes (Thermal Dynamics). However, since then... it stopped derping.

Versions:
deepresonance-1.1.2
mcjtylib-1.8.0

Will comment more if I find more reliable way of reproducing error. Right now I cannot reproduce.

**Comment by McJty** [comment]
I know that the railcraft hidden block is known to occasionally cause issues with other mods. Not sure exactly what the reason here would be though
