### ISSUE TITLE
Server Console Spam possibly leading to other issues

### ISSUE THREAD

**Issue by b0bst3r** [McJty/DeepResonance#68]
Console spam =  http://i.imgur.com/TprBUiT.png

Those blocks are : 
http://i.imgur.com/0wI6Dnk.png

Right most column is Z256
Second from right is 255

Not sure why it's spamming, the tanks around the purifier are top left Input (with pipe attached) down into purifier then the tanks are set to loop back up to the top.

Edit- and I just realised all the errors are being printed by eleccore, so not sure if this should be here or @Elec332 issue.

**Comment by McJty** [comment]
Version of MC and all the mods in question?

**Comment by b0bst3r** [comment]
Urgh sorry again logging so many bugs I keep forgetting info.

ElecCore-1.9-1.4.266
deepresonance-1.9.0-1.1.4beta30
rftools-1.9.0-4.46

That eleccore is old I will try the latest 270 and let you know if this is still happening.

**Comment by b0bst3r** [comment]
Still happening with 270 in fact it's worse.

**Comment by b0bst3r** [comment]
Had to break the blocks as it's causing big TPS issues.

**Comment by RealGrep** [comment]
Can confirm the same issue happening here. ElecCore 270, deepresonance-1.9.0-1.1.4beta30.jar and Forge version 1887.

**Comment by b0bst3r** [comment]
I don't know if the same applies to RealGrep but I watched closely when the spamming started and it seemed to occur more when I left the area or logged out, which is odd.  The area isn't chunkloaded so this makes me think that some logic checking is still going on and not unloading with the chunks.  Anyway I thought I'd let you know in case this is helpful.

**Comment by Elec332** [comment]
Yes, this is a chunkloading issue. 
Can you reproduce this with just DeepResonance?

**Comment by b0bst3r** [comment]
[17:34:49] [Client thread/ERROR]: The mod deepresonance (DeepResonance) requires mods [ElecCore] to be available
[17:34:49] [Client thread/ERROR]: Mod deepresonance (DeepResonance) requires [ElecCore@[1.4.264,)]

Wont load without it

**Comment by RealGrep** [comment]
I think he meant just with Deep Resonance and it's dependencies, but no other unrelated mods. XD

**Comment by b0bst3r** [comment]
This is still happening with Forge 1900, ElecCore-1.9-1.4.270 & deepresonance-1.9.0-1.1.4beta30 I will try and re-create with just those mods but I've hardly had any time to do this.

**Comment by slidingmike** [comment]
Have this happening on Deep Resonance Tanks. 

ElecCore 1.9.4 1.1.4beta32
DeepResonance 1.9.4 1.1.4beta32
Forge 1257 Minecraft 1.9.4

[STDOUT]: [elec332.core.multiblock.dynamic.AbstractDynamicMultiBlockWorldHolder:addTile:117]: ERROR!!! Tile at BlockPos{x=6069, y=83, z=5352} is trying to register whilst already being registered!

**Comment by Gunner76th** [comment]
On my server, currently the console spam is becaused by a set of Deep Resonance tanks (#6105) that are stacked together, 3 high, all filled with lava. As long as the area is chunk loaded, there is no issue, however, once the chunk unloads the console begins to spam about the block. Also this only happens when the chunk is loaded and then unloads, as it does not occur after a server restart and the chunk is not initially loaded. 

The tanks in question are in a single column 3 high, all full of lava, placed touching a Tcon smeltery, with the tank blocks only touching seared stone (#8745/0) blocks. 

Server restart, chunk no loaded = no spam
Player visits area, remains in area and chunk is loaded = no spam
Chunk loader active in chunk, player visits then leaves = no spam
Player visits area, causing chunk to load, then leaves chunk causing chunk to unload = spam

**Comment by Gunner76th** [comment]
@b0bst3r can you confirm that the location in your console log spam is the location of one of the Deep Resonance tanks that may or maynot be stacked. I just looked at your image, and you have a very similar setup (Deep Resonance tanks stacked together) as my server has with this same issue. If this is the case, then we might actually be looking at an issue with deep resonance tanks being stacked.

**Comment by Gunner76th** [comment]
After comparing your console spam, to your image of your setup, it does indeed look to be that the Deep Resonance tanks are for whatever reason, causing the error to be thrown.

**Comment by Claycorp** [comment]
Also having the same issue with these tanks. 

Using:
DeepResonance Beta35
ElecCore 292
Minecraft Forge 1987

Tanks are stacked and not part of any tube or pipe network. The are only touching the Tcon pattern storage and the walls that are stone and chiseled cobble or stone.

http://pastebin.com/v7YJbcTY
https://pbs.twimg.com/media/CnIrRRAVMAAi6Hf.jpg

**Comment by Claycorp** [comment]
Just an update. It seems like stacking tanks upwards is the worst thing to do. Someone on our server had a 3x3 tank with no center and a pipe down the middle and getting near it would make you lose almost all FPS, spam your client with http://pastebin.com/B235apFA and make that area unplayable till destroyed. I have no idea how it was set up exactly beyond that because there was no way to inspect it at all with 0-10 FPS.

I did notice the bottom tank the lava inside would just constantly quickly lower down to almost empty and and reset to the same level.

This issue really needs to get fixed ASAP as it makes servers with this into a lagmine mess.

**Comment by SniperHauss89** [comment]
Hi, I know this is maybe going to throw a monkey wrench into things since this issue is presumed to have started with 1.9/1.10 but I'm getting this spam with the last 1.7.10 version of Deep Resonance. It hasn't been causing any TPS issues though and the tanks aren't stack vertically they were lined up horizontally and there is 5 of them. there are 3 more that aren't connected but serving individual purposes and don't cause console spam.

Deep Resonance 1.1.4 (1.7.10 release)
1.7.10-1.4.294
mcjtylib-1.8.1
forge 1614

**Comment by Claycorp** [comment]
I take it that this issue isn't a priority because it's been 4 months and many people have notified you of the problem and there has been no comment on if its getting fixed or not. If you can't figure out why it's broken perhaps an alternate fix till you can? This isn't a 'Oh you can't make this decorative block' issue. This is a serious issue that is plaguing all sorts of people and servers to the point of causing major problems. You can't just push this to the side.

Us Server admins & players have done everything we can. You need to communicate with us if you need more information. 
All the issues that are for this problem: 
#68 (This one)
#106 
Elecs-Mods/ElecCore#37
Elecs-Mods/ElecCore#47
BreakfastCraft/Spilled-Juice-Modpack#32

If this isn't going to get fixed or nobody is going to communicate from the dev side people are going to stop using it.

**Comment by McJty** [comment]
It is actually a priority and we're busy looking into it.
Problem is that it is a hard issue to crack since neither I nor Elec can reproduce this. So we have to guess as to what is wrong

**Comment by Claycorp** [comment]
Thank you for giving us an update. Would you like any more information at all? I have a server with the problem and will be willing to set up a test instance if needed with a debug version.

**Comment by McJty** [comment]
Perhaps but at the moment @Elec332 is looking into the issue in detail. Let him first have a few more looks at this to see if he can crack this nut. If not we might add more diagnostics to the mod (configurable) so that you guys can help us out with this

**Comment by Gunner76th** [comment]
@McJty when you say that you are not able to reproduce the issue, are you stating that when you setup a server instance (NOT a single player instance) in the same configuration as those of who have reported the error and reported what mods or modpack we are using, and then layed out the tanks as described (both by description and from the photos the one user submitted) and then using the chunk loading methods that I posted cause the error back on July 4th, that you are unable to see the console spam output?
I believe this is an issue that will only be seen when you are running the mod on an actual server environment and then connect to said server with a client. My server group has several Youtubers who do their own "Let's Play" series, and not one of them has reported this error when they have played in single player.

**Comment by McJty** [comment]
I have tested this in a server setup (local server) and was unable to reproduce it.

**Comment by Fey142** [comment]
If you want I can share my world and mods, constant spam every minute

**Comment by Fey142** [comment]
After the rewrite this is what is happening now: http://pastebin.com/HzZs3YS1
Unlike before when it was in spikes it is now constant spam (2-3 TPS when I login and it crashes after a few moments due to the lag that accumulates - [13:06:52] [Server Watchdog/FATAL]: A single server tick took 60,00 seconds (should be max 0,05)
[13:06:52] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.)

**Comment by lilmoefow** [comment]
Was this fix merged into the 1.7.10 version of Deep Resonance aswell?

**Comment by McJty** [comment]
No it wasn't

**Comment by lilmoefow** [comment]
I guess i should have asked this as well.  Will it be merged into the 1.7.10 version?

**Comment by McJty** [comment]
Since this was a total rewrite we don't have plans to merge this into the 1.7.10 version. Also is it actually needed on 1.7.10? I don't remember seeing this issue there

**Comment by lilmoefow** [comment]
I am not 100% positive it is the exact same issue.  I am only drawing this conclusion because of this error that was constantly being thrown in the server console

ERROR!!!  Tile at (2702,62,518) is trying to register whilst already being registered!

I logged onto the server and teleported to those coordinates and set up was all of the machines from Deep Resonance.  It consisted of about 9 tanks and a few other machines. ( I have never used the mod personally so i don't know exactly how to describe it, have been waiting to use the 1.10.2 versions).  Had to break the device down to get the server to respond.


ElecCore-1.7.10-1.4.294
deepresonance-1.1.4
 Forge 1.7.10 10.13.4.1614

Im really just take wild shots in the dark and putting 2 and 2 together.
