### ISSUE TITLE
[Request] Valves should respect redstone in some way

### ISSUE THREAD

**Issue by Hexicube** [McJty/DeepResonance#85]
As it stands, the most effective way to automate the moving of a fluid after being refined with a laser is by breaking the block, since there's no way to remove the fluid without risking mixing from the valve.

By blocking liquid transfer when a redstone signal is present, automated power production becomes possible without resorting to either 100mb chunks on the laser (which is horribly inefficient) or an external mod.

**Comment by McJty** [comment]
I added redstone mode support for the valve. However the default is ignored. However, in order to avoid the problem of placing the valve and it immediatelly sending liquid down I changed the default quality limits to 100% for all three settings. That way it is unlikely to start sending liquids to the tank below immediatelly
